title: Ajinkya Bankar
logo: /assets/img/headshot.png
description: Jacksonville, FL, United States.
email: ajinkya_003 at yahoo dot com
show_downloads: false
google_analytics: G-CDD16HC11T
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-target-blank

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: ""
    icon: <a href="https://www.linkedin.com/in/ajinkyabankar"><img src="https://img.shields.io/badge/-LinkedIn-0072b1?&style=flat&logo=linkedin&logoColor=white" /></a>
  - name: ""  
    icon: <a href="https://scholar.google.com/citations?user=izR3f94AAAAJ&hl=en"><img src="https://img.shields.io/badge/Google%20Scholar-orangered?style=flat&logo=Google%20Scholar&logoColor=white" /></a>



# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
